captcha_handler:
  assets:
    prefix_image_path: '%kernel.project_dir%/public/bundles/captchahandler/images/default-captcha-picture-'
    puzzle_path: '%kernel.project_dir%/public/bundles/captchahandler/images/default-puzzle-picture.png'
  dimensions:
    image_width: 350
    image_height: 200
    puzzle_width: 80
    puzzle_height: 50
    precision: 2
