captcha_handler:
  assets:
    image_path: 'assets/images/default-captcha-picture.png'
    puzzle_path: 'assets/images/default-puzzle-picture.png'
  dimensions:
    image_width: 350
    image_height: 200
    puzzle_width: 80
    puzzle_height: 50
