services:
    VdubDev\CaptchaHandler\Domain\AntiSpam\Puzzle\PuzzleChallenge:
        arguments:
            $imagePath: '%captcha_handler.assets.image_path%'
            $puzzlePath: '%captcha_handler.assets.puzzle_path%'
            $imageWidth: '%captcha_handler.dimensions.image_width%'
            $imageHeight: '%captcha_handler.dimensions.image_height%'
            $puzzleWidth: '%captcha_handler.dimensions.puzzle_width%'
            $puzzleHeight: '%captcha_handler.dimensions.puzzle_height%'
            $precision: '%captcha_handler.dimensions.precision%'